Specflow agent customization example
reportportal/example-net-specflow pull request #2
Opened 2016-12-28 05:05 UTC by aliaksandrbasau

The pull request will resolve #1. Hooks1.cs contains examples of how to add tags to feature and scenario on runtime, add scenario outline parameters to scenario name on RP, attach screenshot of the desktop at the end of scenario.

2016-12-28 12:10 UTC, nvborisenko requested changes
* don't use nunit
* remove limitations part

2016-12-28 12:10 UTC, nvborisenko commented on src/Example.SpecFlow/Hooks/Hooks1.cs
> +        private static void ReportPortalAddin_BeforeScenarioStarted(object sender, TestItemStartedEventArgs e)
I think we should not use nunit in customizations to show examples. Unit provider might be changes and this example will become incorrect.
Let's change this code to show:
* how to modify description
* how to add custom tags

2016-12-28 12:10 UTC, nvborisenko commented on src/Example.SpecFlow/Hooks/Hooks1.cs
> +            // Workaround for 1024 characters restriction on the test item description
All limitations should be handled at agent level.

2016-12-28 12:10 UTC, nvborisenko commented on src/Example.SpecFlow/Hooks/Hooks1.cs
> +            // Workaround for 256 characters restriction on the test item name
Agent should cut test `name` and `description`. I submitted issue #2 to resolve it.

2016-12-28 14:43 UTC, aliaksandrbasau commented
I introduced the dependency on NUnit in order to add scenario parameters to scenario name. It's not possible to get scenario parameters from SpecFlow and the only way to do it is to get them from unit provider. It will not be possible to implement the functionality without NUnit and it will need to be removed it completely. I consider this functionality quite useful since you will not be able to distinguish scenarios with parameters from each other on Report Portal and auto-analysis will not work.
I would still consider leaving the dependency on NUnit in place just to have an example of how to make scenario names unique on RP.

Please let me know what you think.

The limitation parts will be removed. I would implement them on [client-net](https://github.com/reportportal/client-net) library level (not SpecFlow agent level) since it affects all .NET agents.

2016-12-29 10:27 UTC, nvborisenko commented
Reflect input parameters in test name is useful, but this is not general case. Here we need provide simple example of customization.
Let's share nunit specific stuff as code snippets. Somewhere in documentation we will reflect all useful snippets, but we will not use these snippets in code. Example project should be simple.

And agree with cutting length in client, not in agent.

2017-01-10 12:38 UTC, nvborisenko approved these changes

2017-01-10 12:38 UTC, merged

2017-01-10 12:39 UTC, nvborisenko commented
Thanks for understanding.